# The pubspec.yaml file specifies basic information about your app, such as its current version,
# its dependencies, and the assets with which it will ship.

name: namer_app
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.1.0
  font_awesome_flutter: ^10.3.0
  flutter_widget_from_html: ^0.14.9
  readmore: ^2.2.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets\icons\fefu.jpg'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/presentation_files/